### ISSUE TITLE
Link broken.

### ISSUE THREAD

**Issue by tjiangHIT** [PacificBiosciences/sv-benchmark#1]
Hi Armin，
Thanks for your work, but I thought I would let you know that the link of **.fastq** file is broken: _ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/PacBio_CCS_15kb/HG002.15kb.Q20.tar.gz_.
Tao.

**Comment by armintoepfer** [comment]
Hi Tao,

thank you. Indeed GIAB removed it. That's painful of them to remove data that is conveniently tar'd.
Please proceed and download the individual fastq files...When I find time, I will update the instructions.

If you have time, please send a PR to fix my download step and I will merge it.

Armin
