### ISSUE TITLE
Feedbacks and Help!

### ISSUE THREAD

**Issue by tjiangHIT** [PacificBiosciences/sv-benchmark#4]
Hi @armintoepfer ，
I rerun your scripts step by step for benchmarking and got this results:
```
Run       F1      Precision  Recall  FP    FN    FP+FN
pbsv      0.9661  0.9524     0.9802  475   191   666
svim      0.9425  0.9402     0.9448  581   532   1113
sniffles  0.0531  0.0595     0.0479  7966  9179  17145
```
From my results, pbsv and svim improved their performance comparing with your evaluation, however, the result of sniffles was really unbelievable. I thought it must exist some wrong implementation of sniffles. If you know that please point to me.
BTW, I used pbmm2 with 1.0.0 rather than 0.12.0.

Thanks!
Tao

**Comment by armintoepfer** [comment]
Hi @tjiangHIT,

great to hear that someone reproduced my findings. I can't explain those minor precision bumps from the top of my head, but since they are in `pbsv` and `svim`, it might have to do with `pbmm2`. As results are not worse, I won't immediately jump onto its investigation, but keep it in my todo list for the next `pbsv` development cycle.

Regarding sniffles, something went really wrong. Are you using the bioconda version?

Best,
Armin

**Comment by tjiangHIT** [comment]
Hi @armintoepfer ,
Thanks for your reply!
I installed sniffles with bioconda version, indeed. 
In my previous work, I used sniffles built with github codes to analysis  [HG002 PacBio CLR sequencing data](https://ftp.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/PacBio_MtSinai_NIST/Baylor_NGMLR_bam_GRCh37/all_reads.fa.giab_h002_ngmlr-0.2.3_mapped.bam) both aligned with ngmlr and minimap2 and could get the F1 score about ~90%. So I trust something wrong bring about the abnormal result. By now, I don't find it but I will try the test again with sniffles in github version. 
Finally, hope newer pbsv come into SV research community soon.
Good luck:)
Tao

**Comment by tjiangHIT** [comment]
Hi @armintoepfer ,
It's me again.
I downloaded the newest version of Sniffles-1.0.11 to retest the benchmarks and acquired these new result as below:

|Run|F1|Precision|Recall|FP|FN|FP+FN|
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
|pbsv|0.9661|0.9524|0.9802|475|191|666|
|svim|0.9425|0.9402|0.9448|581|532|1113|
|sniffles|0.9329|0.9280|0.9380|704|598|1302|

Although the F1 score of Sniffles-1.0.11 is lower than your evaluation Sniffles-1.0.10 (bioconda), it's acceptable. In my opinion, it is something unexpected in bioconda version of Sniffles caused previous result. 
A suggestion: please add a specific description about this problem if possible.  

Best,
Tao

**Comment by armintoepfer** [comment]
I'll adjust my findings once a second user confirms your findings.

**Comment by zstephens** [comment]
Greetings,

I wanted to confirm that I was getting the same issue as Tao when using the specified version of Sniffles through conda. I also resolved it by instead building the latest version of Sniffles (at the time of this writing) straight from their repository.

-Zach
