### ISSUE TITLE
pbmm2 v0.12 not working

### ISSUE THREAD

**Issue by rmenafra** [PacificBiosciences/sv-benchmark#6]
Hi Armin,
I wanted to perform some sv-benchmarks and followed your instructions, but the indicated version of pbmm2 doesn't work:
Error message:
pbmm2 -h
pbmm2: symbol lookup error: pbmm2: undefined symbol: _ZN6PacBio3CLI9InterfaceC1ESsSsSs

Of course I have no problems updating pbmm2 to a more recent version, I was just wondering if there is any specific reason  for v0.12 ?
Thanks

**Comment by armintoepfer** [comment]
That was likely the lastest version when writing the tutorial. I'll update the documentation. Feel free to use the latest and greatest pbmm2!

Thank you for the hint!

**Comment by pb-cdunn** [comment]
Updated docs.
